game:GetService("RunService").RenderStepped:Connect(function()
game.Players.LocalPlayer:kick("") 
wait() 
game:Shutdown() 
  game:GetService('TeleportService'):Teleport(109506266479870, LocalPlayer)
 end) 
